DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS receipts;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS goods;

CREATE TABLE customers (
	Id INTEGER PRIMARY KEY,
	LastName VARCHAR(100) NOT NULL, 
	FirstName VARCHAR(100) NOT NULL);

CREATE TABLE goods (
	Id VARCHAR(100) PRIMARY KEY,
	Flavor VARCHAR(100) NOT NULL,
	Food VARCHAR(100) NOT NULL,
	Price DECIMAL(5,2) NOT NULL);

CREATE TABLE receipts(
	ReceiptNumber INTEGER PRIMARY KEY,
	`Date` DATE NOT NULL,
	CustomerId INTEGER NOT NULL,
	FOREIGN KEY (CustomerId) REFERENCES customers (Id));

CREATE TABLE items (
	Receipt INTEGER NOT NULL,
	Ordinal INTEGER NOT NULL,
	Item VARCHAR(100) NOT NULL,
	FOREIGN KEY (Receipt) REFERENCES receipts (ReceiptNumber),
	FOREIGN KEY (Item) REFERENCES goods (Id),
	PRIMARY KEY (Receipt, Ordinal));

