DROP TABLE IF EXISTS Reservations;
DROP TABLE IF EXISTS Rooms;

CREATE TABLE Rooms(
RoomId CHAR(3) PRIMARY KEY,
roomName VARCHAR(20) NOT NULL,
beds INTEGER NOT NULL,
bedType VARCHAR(10) NOT NULL,
maxOccupancy INTEGER,
basePrice DECIMAL,
decor VARCHAR(20)
);

CREATE TABLE Reservations(
`Code` INTEGER PRIMARY KEY,
Room CHAR(3) NOT NULL,
CheckIn DATE,
CheckOut DATE,
Rate DECIMAL NOT NULL,
LastName VARCHAR(20),
FirstName VARCHAR(20),
Adults INTEGER,
KIDS INTEGER,
FOREIGN KEY (Room) REFERENCES Rooms (RoomId)
);